# Generated by Django 3.2.7 on 2021-10-01 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20210925_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clerk_user',
            options={'verbose_name': 'Clerk', 'verbose_name_plural': 'Clerks'},
        ),
        migrations.AlterModelOptions(
            name='hod_user',
            options={'verbose_name': 'HOD', 'verbose_name_plural': 'HODS'},
        ),
        migrations.AlterModelOptions(
            name='student_user',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher_user',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterField(
            model_name='teacher_user',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
