# Generated by Django 3.2.7 on 2021-10-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_auto_20211003_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.department'),
        ),
    ]
