# Generated by Django 3.2.7 on 2021-10-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_alter_student_user_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_user',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
