# Generated by Django 3.2.7 on 2021-10-08 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_alter_student_user_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_user',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='assignment.batch'),
        ),
    ]
