# Generated by Django 3.2.7 on 2021-10-08 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_alter_student_user_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='assignment.department'),
        ),
    ]
