# Generated by Django 3.2.7 on 2021-10-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0017_auto_20211011_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subject',
            new_name='subject_name',
        ),
    ]
