# Generated by Django 3.2.7 on 2021-10-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0019_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='name',
        ),
        migrations.AlterField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='semester_course', to='assignment.Course'),
        ),
    ]
