# Generated by Django 3.2.7 on 2021-10-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0020_auto_20211013_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='name',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
