# Generated by Django 3.2.7 on 2021-10-17 10:24

import assignment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0023_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Assignment_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=assignment.models.assignement_create_path)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='assignment.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_of_student', to='assignment.student_user')),
            ],
            options={
                'verbose_name': 'Assignment_Submission',
                'verbose_name_plural': 'Assignment_Submissions',
            },
        ),
    ]
