# Generated by Django 3.2.7 on 2021-10-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0024_auto_20211017_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='assignment.assignment'),
        ),
    ]
