# Generated by Django 3.2.7 on 2021-10-20 10:28

import assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0025_alter_assignment_submission_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_submission',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment_submission',
            name='file',
            field=models.FileField(upload_to=assignment.models.assignement_submit_path),
        ),
    ]
