# Generated by Django 3.2.7 on 2021-10-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0027_alter_assignment_submission_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_submission',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
