# Generated by Django 3.2.7 on 2021-10-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0029_assignment_submission_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment_submission',
            name='submitted',
        ),
    ]
